# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setMinimumSize(QtCore.QSize(450, 600))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_picture = QtWidgets.QLabel(self.centralwidget)
        self.label_picture.setGeometry(QtCore.QRect(160, 100, 141, 211))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_picture.setFont(font)
        self.label_picture.setText("")
        self.label_picture.setPixmap(QtGui.QPixmap("Hangman1.png"))
        self.label_picture.setObjectName("label_picture")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(150, 30, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_guess = QtWidgets.QLabel(self.centralwidget)
        self.label_guess.setGeometry(QtCore.QRect(30, 410, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(13)
        self.label_guess.setFont(font)
        self.label_guess.setObjectName("label_guess")
        self.entry_guess = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_guess.setGeometry(QtCore.QRect(130, 420, 131, 22))
        self.entry_guess.setText("")
        self.entry_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.entry_guess.setObjectName("entry_guess")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(300, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.label_word = QtWidgets.QLabel(self.centralwidget)
        self.label_word.setGeometry(QtCore.QRect(30, 340, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        self.label_word.setFont(font)
        self.label_word.setText("")
        self.label_word.setAlignment(QtCore.Qt.AlignCenter)
        self.label_word.setObjectName("label_word")
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(20, 470, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(7)
        self.label_message.setFont(font)
        self.label_message.setText("")
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(300, 410, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hangman"))
        self.label_title.setText(_translate("MainWindow", "HANGMAN"))
        self.label_guess.setText(_translate("MainWindow", "Guess:"))
        self.pushButton_reset.setText(_translate("MainWindow", "RESET"))
        self.pushButton_submit.setText(_translate("MainWindow", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
